allowLineBreaksInTitles: true
color: null
description: null
fieldLayouts:
  f8311f0e-1514-4d66-8345-6f63650b8cd9:
    cardThumbAlignment: end
    cardView:
      - slug
    generatedFields:
      -
        handle: ''
        name: ''
        template: ''
        uid: 0de25055-f09a-4265-a101-f7a02bde823a
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-12T22:45:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f3b525d7-249d-4e37-a7d0-1b545abd0bdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-12T22:49:17+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 60319308-2629-4009-800b-790f1222826e # Image
            handle: photo
            instructions: null
            label: Photo
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60a315ba-e6f5-4305-9e90-583693ae935e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-23T16:15:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: h1Heading
            instructions: null
            label: 'H1 Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d617ab28-79f7-478f-9958-74caf8319a0e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-12T22:49:17+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a095f216-7e6f-4b38-93fe-ef54b945634f # Rich Text
            handle: description
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89b3652b-4786-4408-ae91-8243f790a312
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0cf7a313-9248-4a98-842c-3635f4104aca
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-23T16:46:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: philosophyTitle
            instructions: null
            label: Title
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a026f28c-6819-4e22-87e7-85552f75460a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-23T16:46:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 62f2e7a8-cd3b-4fd3-8551-07fd042891a1 # CKEditor
            handle: philosophyDescription
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93967720-bb6f-4941-91b8-1def41b93333
            userCondition: null
            warning: null
            width: 100
        name: 'My Philosophy'
        uid: 80a0b194-2353-4203-8f8f-9395b838e5da
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-23T16:15:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: ctaTitle
            instructions: null
            label: Title
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 080a984b-c0d6-4653-9467-d2dac5d29b2f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-23T16:11:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: ctaDescription
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2e6f5af-0cc1-460f-bef8-605cd86999b3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-23T16:11:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c42f6a1e-b175-47f2-a78a-73e32b9520ed # Button
            handle: ctaButton
            instructions: null
            label: Button
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af6a2ec3-4482-48aa-a39c-a11f00ee6b7e
            userCondition: null
            warning: null
            width: 100
        name: 'Call to Action'
        uid: 282fa125-c1e6-43ac-be6f-8dfc948bcc5c
        userCondition: null
    thumbFieldKey: null
handle: aboutPage
hasTitleField: true
icon: address-card
name: 'About Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
