allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  656ad071-4403-4de6-aa8f-8caef6707ba7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-13T00:38:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: eyebrowHeading
            instructions: null
            label: 'Eyebrow Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ca4d2d9-0773-4673-a769-877038eaea83
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-13T00:38:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: h2Heading
            instructions: null
            label: 'H2 Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39be1f72-e366-4e17-a92a-85ae145523c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-13T00:38:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: h2Subheading
            instructions: null
            label: 'H2 Subheading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43e0d3e5-4d50-426d-ac50-5e5547b6cc52
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59df48e9-3391-4bd0-a284-e39597178645
        userCondition: null
    thumbFieldKey: null
handle: myApproach
hasTitleField: false
icon: map-location-dot
name: 'My Approach'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
