allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  c457ab73-29b4-422e-bb7a-3e17815d15c6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-15T14:45:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 62f2e7a8-cd3b-4fd3-8551-07fd042891a1 # CKEditor
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e63d706-ba0e-4ab7-9366-0a61d7787202
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a2457939-7e10-4ce6-89dd-51ac14b7052e
        userCondition: null
    thumbFieldKey: null
handle: projectDetails
hasTitleField: false
icon: null
name: 'Project Details'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
