columnSuffix: null
handle: button
instructions: null
name: Button
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - '1'
            -
              - allowAnchors
              - '1'
            -
              - allowCustomSchemes
              - ''
  types:
    - url
    - email
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
