fieldLayouts:
  b0bb7df1-08cd-4c81-ab4f-0d04dbf4392b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-21T15:30:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: linkedinURL
            instructions: null
            label: 'LinkedIn URL'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a18ca42-9c90-49d5-af87-3b62886373f0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-21T15:30:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: githubURL
            instructions: null
            label: 'Github URL'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f105de8-811d-4c64-9934-d5f7f23bce0c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-21T15:30:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: instagramURL
            instructions: null
            label: 'Instagram URL'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e556446-c766-4ad3-b276-de765610aa1e
            userCondition: null
            warning: null
            width: 100
        name: 'Social Media'
        uid: a41645d6-ba69-47e9-a0d9-e8b5cfe25f57
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-21T15:34:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: logoSVGBlack
            instructions: 'Enter the image data URI, for example: data:image/png;base64,...'
            label: 'Logo SVG Black'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05e2eaae-93e5-43d8-b8d8-999454da4cdf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-21T15:34:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: logoSVGWhite
            instructions: 'Enter the image data URI, for example: data:image/png;base64,...'
            label: 'Logo SVG White'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10e3bff0-8bbb-4755-a3ff-10c8f1be6222
            userCondition: null
            warning: null
            width: 100
        name: Logos
        uid: 44da3537-a7eb-41ed-8772-058c94a17e9a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-21T15:38:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f79a7913-9874-43d3-ac98-cdb0f6d8bcdb # Email
            handle: email
            instructions: null
            label: Email
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51d5214b-4298-435d-896d-b16c180e31dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-21T15:37:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: phoneNumber
            instructions: null
            label: 'Phone Number'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04775ab8-6c0c-42bd-92d7-0f3c45fe06c5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-22T12:50:40+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: location
            instructions: null
            label: Location
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fd93ad9-87e5-4713-9fdb-c4eac369f891
            userCondition: null
            warning: null
            width: 100
        name: 'Contact '
        uid: 17a1c161-4baf-40da-9030-4ba18a7851bd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-22T13:23:18+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 62f2e7a8-cd3b-4fd3-8551-07fd042891a1 # CKEditor
            handle: tagline
            instructions: null
            label: Tagline
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00ba4f00-7e73-4771-9226-776d7f93b47d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-22T14:36:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 62f2e7a8-cd3b-4fd3-8551-07fd042891a1 # CKEditor
            handle: copywrite
            instructions: null
            label: Copywrite
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dbc5b18-c1a0-4867-ab3c-0bdc278c4721
            userCondition: null
            warning: null
            width: 100
        name: Footer
        uid: 4c6f3b51-a555-4681-8248-bbbffa377b5a
        userCondition: null
    thumbFieldKey: null
handle: globalOptions
name: 'Global Options'
sortOrder: 2
