fieldLayouts:
  64d3bc7c-7c06-430e-a65b-39efa92d48a8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-12T22:57:08+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a81cde5c-2623-4caa-9a50-d4ed47522578 # Text
            handle: description
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c3c4dac-c2d7-4250-a3ec-860f8ac0e756
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: c832902f-342a-4589-81a1-64ba9e7739e4
        userCondition: null
    thumbFieldKey: null
handle: siteInfo
name: 'Site Info'
sortOrder: 1
