currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: image
layout: ab495ce4-69f7-4037-8cf0-7913c46705f2 # Default
level: 1
newWindow: false
parent: null
prevLabel: Assets
prevLevel: 1
prevParent: null
prevUrl: assets
sortOrder: 5
type: craft
url: assets
