currLabel: FreeNav
customIcon: null
enabled: true
handle: free-nav
icon: /var/www/html/vendor/justinholtweb/craft-free-nav/src/icon-mask.svg
layout: ab495ce4-69f7-4037-8cf0-7913c46705f2 # Default
level: 1
newWindow: false
parent: null
prevLabel: FreeNav
prevLevel: 1
prevParent: null
prevUrl: free-nav
sortOrder: 6
type: plugin
url: free-nav
