currLabel: Schemas
customIcon: null
enabled: true
handle: schemas
icon: null
layout: ab495ce4-69f7-4037-8cf0-7913c46705f2 # Default
level: 2
newWindow: false
parent: b6419a00-f290-44ab-aa48-7511b5c2ca39
prevLabel: Schemas
prevLevel: 2
prevParent: b6419a00-f290-44ab-aa48-7511b5c2ca39
prevUrl: graphql/schemas
sortOrder: 7
type: craft
url: graphql/schemas
