currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: gear
layout: ab495ce4-69f7-4037-8cf0-7913c46705f2 # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 11
type: craft
url: settings
