currLabel: Tokens
customIcon: null
enabled: true
handle: tokens
icon: null
layout: ab495ce4-69f7-4037-8cf0-7913c46705f2 # Default
level: 2
newWindow: false
parent: 469d6dab-2262-4cc3-bcfd-f05e54db6db2
prevLabel: Tokens
prevLevel: 2
prevParent: 469d6dab-2262-4cc3-bcfd-f05e54db6db2
prevUrl: graphql/tokens
sortOrder: 14
type: craft
url: graphql/tokens
