defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 64fd8540-7793-4c6d-82c7-feab5c6e1f96 # Portfolio Items
handle: portfolio
maxAuthors: 1
minAuthors: 1
name: Portfolio
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  92800916-3004-44ea-9398-6192688fca6a: # hi-hatconsulting
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'portfolio/{slug}'
structure:
  maxLevels: null
  uid: 1da7b6d1-3646-49e2-a5e7-78391822c068
type: structure
