defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 965cbbf1-8ce4-4177-b46b-89eeda7b35c6 # Portfolio Item
handle: portfolio
maxAuthors: 1
minAuthors: 1
name: Portfolio
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  92800916-3004-44ea-9398-6192688fca6a: # hi-hatconsulting
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'portfolio/{slug}'
structure:
  maxLevels: null
  uid: 00eb8476-cb14-429c-be59-5359f328bb7a
type: structure
