defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: be4822e1-f600-4024-8bb9-20aa3bed0a1a # Testimonial Item
handle: testimonials
maxAuthors: 1
minAuthors: 1
name: Testimonials
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  92800916-3004-44ea-9398-6192688fca6a: # hi-hatconsulting
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'testimonials/{slug}'
structure:
  maxLevels: null
  uid: 21859461-f796-44ef-99b8-b6fbdd2d2f75
type: structure
